# tekton/kaniko-sa.yml
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  annotations:
    tekton.dev/docker-0: https://index.docker.io/v1/
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": "your-dockerhub-username",
          "password": "your-personal-access-token",
          "auth": "$(echo -n 'your-dockerhub-username:your-personal-access-token' | base64)"
        }
      }
    }
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kaniko-sa
secrets:
  - name: dockerhub-secret