# tekton/taskrun.yml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-run-1
spec:
  pipelineRef:
    name: docker-build-pipeline
  params:
    - name: IMAGE
      value: docker.io/ishusharmaishan/rails-postgres-app # Updated with your Docker Hub username and image name
    - name: CONTEXT
      value: .
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: tekton-pvc
  serviceAccountName: kaniko-sa